export interface GeneralStats {
    totalClosedAnnouncements: number,
    totalIncome: number,
    topDealName: string,
    topDealStatementType: string,
    topDealPrice: number,
    topDealRealtorName: string,
    topDealCustomerName: string,
    topDealSoldDate: string,
    topRealtorNameFirst: string,
    topRealtorDealsFirst: number,
    topRealtorIncomeFirst: number,
    topRealtorNameSecond: string,
    topRealtorDealsSecond: number,
    topRealtorIncomeSecond: number,
    topPropertyTypeNameFirst: string,
    topPropertyTypeCntFirst: number,
    topPropertyTypeAvgPriceFirst: number,
    topPropertyTypeNameSecond: string,
    topPropertyTypeCntSecond: number,
    topPropertyTypeAvgPriceSecond: number,
    topClientNameFirst: string,
    topClientDealsFirst: number,
    topClientSpentFirst: number,
    topClientNameSecond: string,
    topClientDealsSecond: number,
    topClientSpentSecond: number
}